services:
  pocketbase:
    image: ${IMGAGE_REPO}/pocketbase:latest
    volumes:
      - database:/pb/pb_data
    environment:
      - CORS_ENABLED=true
      - CORS_ORIGIN=https://${DOMAIN_NAME},https://stage.${DOMAIN_NAME},${CORS_ORIGIN}
      - PUBLIC_URL=https://pb.${DOMAIN_NAME}
      - VAPID_PUBLIC_KEY=${VAPID_PUBLIC_KEY}
      - VAPID_PRIVATE_KEY=${VAPID_PRIVATE_KEY}

    networks:
      - traefik-public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.port=8080"
        - "traefik.http.routers.${STACKNAME}-pocketbase.rule=Host(`pb.${DOMAIN_NAME}`)"
        - "traefik.http.routers.${STACKNAME}-pocketbase.entrypoints=web,websecure"
        - "traefik.http.routers.${STACKNAME}-pocketbase.tls=true"
        - "traefik.http.routers.${STACKNAME}-pocketbase.tls.certresolver=letsencrypt"
        - "traefik.http.services.${STACKNAME}-pocketbase.loadbalancer.server.port=8080"

  vue:
    image: ${IMGAGE_REPO}/vue:latest
    depends_on:
      - pocketbase
    environment:
      - API_URL=https://pb.${DOMAIN_NAME}
      - VAPID_PUBLIC_KEY=${VAPID_PUBLIC_KEY}
    networks:
      - traefik-public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.port=80"
        - "traefik.http.routers.${STACKNAME}-vue.rule=Host(`app.${DOMAIN_NAME}`)"
        - "traefik.http.routers.${STACKNAME}-vue.entrypoints=web,websecure"
        - "traefik.http.routers.${STACKNAME}-vue.tls=true"
        - "traefik.http.routers.${STACKNAME}-vue.tls.certresolver=letsencrypt"
        - "traefik.http.services.${STACKNAME}-vue.loadbalancer.server.port=80"

  vue-staging:
    image: ${IMGAGE_REPO}/vue:${STAGE_TAG:-stage}
    depends_on:
      - pocketbase
    environment:
      - API_URL=https://pb.${DOMAIN_NAME}
      - VAPID_PUBLIC_KEY=${VAPID_PUBLIC_KEY}
    networks:
      - traefik-public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.port=80"
        - "traefik.http.routers.${STACKNAME}-vue-staging.rule=Host(`stage.${DOMAIN_NAME}`)"
        - "traefik.http.routers.${STACKNAME}-vue-staging.entrypoints=web,websecure"
        - "traefik.http.routers.${STACKNAME}-vue-staging.tls=true"
        - "traefik.http.routers.${STACKNAME}-vue-staging.tls.certresolver=letsencrypt"
        - "traefik.http.services.${STACKNAME}-vue-staging.loadbalancer.server.port=80"

volumes:
  database:
    external: true
    name: shared_${STACKNAME}_database

networks:
  traefik-public:
    driver: overlay
    external: true
    attachable: true
