

services:
  pocketbase:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "8090:8090"
    volumes:
      - ./server:/server
    healthcheck: # optional, recommended since v0.10.0
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5

  vue:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./node_modules:/app/node_modules
      - ./src:/app/src
    depends_on:
      - pocketbase
