name: Docker Image CI Staging

on:
  push:
    branches: [ "prod" ]
  pull_request:
    branches: [ "prod" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Set TAG
      run: |
        IMG=ghcr.io/${GITHUB_REPOSITORY@L}
        echo "IMG=$IMG" >> $GITHUB_ENV
        
    - uses: actions/checkout@v4
            
    - name: Log in to ghcr.io
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      
    - name: Build the pocketbase Docker image
      run: docker build -t ${{ env.IMG }}/pocketbase:latest ./server

    - name: Push pocketbase image to GHCR
      run: docker push ${{ env.IMG }}/pocketbase:latest

    - name: Build the vue Docker image
      run: docker build -t ${{ env.IMG }}/vue:latest ./server

    - name: Push vue image to GHCR
      run: docker push ${{ env.IMG }}/vue:latest

    - name: Pull Webhook
      run: curl -X POST -k ${{vars.WEBHOOK}}
