name: Docker Image CI Staging

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Set TAG
      run: |
        TAG=stage-$(date +%s)
        IMG=ghcr.io/${GITHUB_REPOSITORY@L}
        echo "TAG=$TAG" >> $GITHUB_ENV
        echo "IMG=$IMG" >> $GITHUB_ENV
        
    - uses: actions/checkout@v4
    - name: Log in to ghcr.io
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      
    - name: Build the pocketbase Docker image
      run: docker build -t ${{ env.IMG }}/pocketbase:${{env.TAG}} -t ${{ env.IMG }}:stage ./server

    - name: Push pocketbase image to GHCR
      run: docker push ${{ env.IMG }}/pocketbase --all-tags

    - name: Build the vue Docker image
      run: docker build -t ${{ env.IMG }}/vue:${{env.TAG}} -t ${{ env.IMG }}:stage .

    - name: Push vue image to GHCR
      run: docker push ${{ env.IMG }}/vue --all-tags

    - name: Pull Webhook
      run: curl -X POST -k ${{vars.WEBHOOK}}?STAGE_TAG=${{env.TAG}}
